
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - model_merge_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - model_merge_network
    environment:
      - DATABASE_URL=your-database-url-here
      - DIRECT_URL=your-direct-url-here
    command: ["npm", "run", "start:dev"] # Or your preferred start command for development

networks:
  model_merge_network:
    driver: bridge